/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-12-02 05:23:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fullcalendar_002d5_4_0.examples;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import reservation.model.vo.Reservation;
import member.model.vo.Member;

public final class full_002dheight_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1606886128596L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1606808284865L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("reservation.model.vo.Reservation");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    	Reservation r = (Reservation)request.getAttribute("reserveAdmin");
    	if(r!=null){
    		//수정인경우만
    		System.out.println("예약날짜 = "+r.getrDate());
    	}
    
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("<link href='/fullcalendar-5.4.0/lib/main.css' rel='stylesheet' />\r\n");
      out.write("<link href='/fullcalendar-5.4.0/lib/resv.css' rel='stylesheet' />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"#\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src='/fullcalendar-5.4.0/lib/main.js'></script>\r\n");
      out.write("<script>\r\n");
      out.write("var selConcept = null;\r\n");
      out.write("$(document).ready(function(){\t\r\n");
      out.write("\t  $(\"div\").removeClass(\"fc-daygrid-event-harness\");\r\n");
      out.write("\t\t$(\"div\").removeClass(\"fc-daygrid-event-harness-abs\");\r\n");
      out.write("\t\t$(\".fc-event-title-container\").parent().parent().parent().remove();\r\n");
      out.write("\t\t$(\".fc-daygrid-event-dot\").parent().remove();\r\n");
      out.write("});\r\n");
      out.write("  document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("\t  $(\"div\").removeClass(\"fc-daygrid-event-harness\");\r\n");
      out.write("\t\t$(\"div\").removeClass(\"fc-daygrid-event-harness-abs\");\r\n");
      out.write("\t\t$(\".fc-event-title-container\").parent().parent().parent().remove();\r\n");
      out.write("\t\t$(\".fc-daygrid-event-dot\").parent().remove();\r\n");
      out.write("    var calendarEl = document.getElementById('calendar');\r\n");
      out.write("    \r\n");
      out.write("    var today = new Date();\r\n");
      out.write("\tconsole.log(\"연도\"+today.getFullYear());\r\n");
      out.write("\tconsole.log(\"월\"+(today.getMonth()+1));\r\n");
      out.write("\tvar year = today.getFullYear();\r\n");
      out.write("\tvar month = (today.getMonth()+1);\r\n");
      out.write("\tvar day = today.getDate();\r\n");
      out.write("\tif(day<10){\r\n");
      out.write("\t\tday=\"0\"+day;\r\n");
      out.write("\t}\r\n");
      out.write("\tconsole.log(\"일\"+day);\r\n");
      out.write("\tvar todayStr = year+\"-\"+month+\"-\"+day;\r\n");
      out.write("\tconsole.log(\"날짜 = \"+todayStr);\r\n");
      out.write("\t\r\n");
      out.write("    var calendar = new FullCalendar.Calendar(calendarEl, {\r\n");
      out.write("      height: '100%',\r\n");
      out.write("      expandRows: true,\r\n");
      out.write("      slotMinTime: '08:00',\r\n");
      out.write("      slotMaxTime: '20:00',\r\n");
      out.write("      //우측상단툴바메뉴조정\r\n");
      out.write("      headerToolbar: {\r\n");
      out.write("        left: 'prev,next today',\r\n");
      out.write("        center: 'title',\r\n");
      out.write("        right: 'dayGridMonth'\r\n");
      out.write("      },\r\n");
      out.write("      initialView: 'dayGridMonth',\r\n");
      out.write("      //초기화 날짜\r\n");
      out.write("      initialDate: todayStr,  //sysdate로 설정 요망\r\n");
      out.write("      navLinks: false, // can click day/week names to navigate views\r\n");
      out.write("      editable: true,//일정 드래그 앤 드랍\r\n");
      out.write("      selectable: true,\r\n");
      out.write("      nowIndicator: true,\r\n");
      out.write("      dayMaxEvents: true, // allow \"more\" link when too many events\r\n");
      out.write("      events: [\r\n");
      out.write("          \r\n");
      out.write("         \r\n");
      out.write("        ]\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("    calendar.render();\r\n");
      out.write("    $('select[name=\"concept\"]').change(function() {\r\n");
      out.write("\r\n");
      out.write("        if ($(this).val() == \"바디프로필\") {\r\n");
      out.write("            picPrice = 10000;\r\n");
      out.write("            console.log(picPrice);\r\n");
      out.write("            selConcept=\"body\";\r\n");
      out.write("        } else if ($(this).val()==\"개인프로필\" ) {\r\n");
      out.write("            picPrice = 5000;\r\n");
      out.write("            console.log(picPrice);\r\n");
      out.write("            selConcept=\"indiv\";\r\n");
      out.write("        } else {\r\n");
      out.write("            picPrice = 15000;\r\n");
      out.write("            console.log(picPrice);\r\n");
      out.write("            selConcept=\"group\";\r\n");
      out.write("        }\r\n");
      out.write("        $(\"#resv-submit-input-text\").attr(\"value\", \"가격: \"+(picPrice + cutPrice + timePrice) + \"원\");\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("    });\r\n");
      out.write("    var resvDate=null;\r\n");
      out.write("    var startDay = 0;\r\n");
      out.write("    var endDay = 0;\r\n");
      out.write("    var test3 = $(\"td[data-date]\");\r\n");
      out.write("    test3.each(function(i){\r\n");
      out.write("\t\t$(this).click(function(e){\r\n");
      out.write("\t\t\tvar inputChkbox = $('input[type=\"checkbox\"]');\r\n");
      out.write("\t\t\tinputChkbox.prop(\"disabled\",false);\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\tconsole.log(test3.eq(i).attr('data-date'));\r\n");
      out.write("\t\t\tresvDate=test3.eq(i).attr('data-date');\r\n");
      out.write("\t\t\t$(\"div[name=r_date]\").attr(\"value\",resvDate);\r\n");
      out.write("\t\t\t$(\"div[name=r_date]\").html(resvDate);\r\n");
      out.write("\t\t\t$(\"input[name=r_date]\").attr(\"value\",resvDate);\r\n");
      out.write("\t\t\tconsole.log($(\"input[name=resvDate]\").val());\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t\t클릭시 resvDate를 디비에 보내 \r\n");
      out.write("\t\t\t\t리스트에 시작시간과 총시간 가져옴\r\n");
      out.write("\t\t\t\t반복문을 돌려서 시간만큼 비활성화\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t$(\".labelchk\").removeClass(\"resv-chk-style-disabled\");\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/printReservedDateTime\",\r\n");
      out.write("\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\tdata:{resvDate:resvDate},\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data.length);\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t\t\t\t\tvar sTime=Number(data[i].sTime);\r\n");
      out.write("\t\t\t\t\t\tvar eTime=Number(data[i].eTime);\r\n");
      out.write("\t\t\t\t\t\t//var timeLabel =document.getElementsByClassName(\"labelchk\");\r\n");
      out.write("\t\t\t\t\t\tvar timeLabel = $(\".labelchk\");\r\n");
      out.write("\t\t\t\t\t\tfor(var i=0;i<timeLabel.length;i++){\r\n");
      out.write("\t\t\t\t\t\t\tvar val = timeLabel.eq(i).attr(\"value\");\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(Number(val)>=sTime && Number(val)<=eTime){\r\n");
      out.write("\t\t\t\t\t\t\t\ttimeLabel.eq(i).addClass(\"resv-chk-style-disabled\");\r\n");
      out.write("\t\t\t\t\t\t\t\t//timeLabel.eq(i).removeClass(\".labelchk\");\r\n");
      out.write("\t\t\t\t\t\t\t\ttimeLabel.eq(i).children().prop(\"disabled\",true);\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},error:function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tconsole.log(selConcept);\r\n");
      out.write("\t\t\t var inputChkbox = $('input[type=\"checkbox\"]');\r\n");
      out.write("\t\t        inputChkbox.unbind(\"click\").bind(\"click\",function(){\r\n");
      out.write("\t\t        \tstartDay=0;\r\n");
      out.write("\t\t        \tendDay=0;\r\n");
      out.write("\t\t        \tinputChkbox.prop(\"checked\",false);\r\n");
      out.write("\t\t        \tinputChkbox.parent().removeClass(\"resv-chk-style\");\r\n");
      out.write("\t\t        \tconsole.log(\"123\");\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \tconsole.log($(this).is(\":checked\"));\r\n");
      out.write("\t\t        \tif(selConcept==\"group\"){\r\n");
      out.write("\t\t        \t\tif($(this).parent().next().children().prop(\"disabled\")==true){\r\n");
      out.write("\t\t        \t\t\talert(\"단체사진은 최소 2시간이 필요합니다.\");\r\n");
      out.write("\t\t        \t\t\tinputChkbox.prop(\"checked\",false);\r\n");
      out.write("\t\t        \t\t}else{\r\n");
      out.write("\t\t        \t\t\t$(this).parent().addClass(\"resv-chk-style\");\r\n");
      out.write("\t\t        \t\t\t$(this).parent().next().children().prop(\"checked\",true);\r\n");
      out.write("\t\t        \t\t\t$(this).parent().next().addClass(\"resv-chk-style\");\r\n");
      out.write("\t\t        \t\t\tconsole.log($(this).parent().next().children().is(\":checked\"));\r\n");
      out.write("\t\t        \t\t\tstartDay=$(this).parent().attr(\"value\");\r\n");
      out.write("\t\t        \t\t\tendDay=$(this).parent().next().attr(\"value\");\r\n");
      out.write("\t\t        \t\t}\r\n");
      out.write("\t\t        \t\t\r\n");
      out.write("\t\t        \t}else if(selConcept==null){\r\n");
      out.write("\t\t        \t\tinputChkbox.prop(\"checked\",false);\r\n");
      out.write("\t\t        \t\talert(\"컨셉을 선택하세요\");\r\n");
      out.write("\t\t        \t\t\r\n");
      out.write("\t\t        \t}else{\r\n");
      out.write("\t\t        \t\t$(this).parent().addClass(\"resv-chk-style\");\r\n");
      out.write("\t\t        \t\tstartDay=$(this).parent().attr(\"value\");\r\n");
      out.write("\t\t        \t\tendDay=$(this).parent().attr(\"value\");\r\n");
      out.write("\t\t        \t}\r\n");
      out.write("\t\t        \t $('#sendstartday').attr(\"value\",startDay);\r\n");
      out.write("\t\t\t\t\t\t$('#sendendday').attr(\"value\",Number(endDay)+1);\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("    \t$('input[type=\"checkbox\"]').click(function(){\r\n");
      out.write("    \t\tif(resvDate==null){\r\n");
      out.write("    \t\t\talert(\"날짜를 먼저 선택하세요\");\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t})\r\n");
      out.write("    });\r\n");
      out.write("  \r\n");
      out.write("  $(\".fc-daygrid-day-frame\").click(function(){\r\n");
      out.write("\t  \r\n");
      out.write("  });\r\n");
      out.write("\twindow.onload=function(){\r\n");
      out.write("\t\t$(\"a[data-navlink]\").removeAttr('data-navlink');\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("  html, body {\r\n");
      out.write("    /*overflow: hidden; /* don't do scrollbars */*/\r\n");
      out.write("    font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("  }\r\n");
      out.write("  html{\r\n");
      out.write("  \toverflow:scroll; width:1920px; height:1080px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #calendar-container {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .fc-header-toolbar {\r\n");
      out.write("    /*\r\n");
      out.write("    the calendar will be butting up against the edges,\r\n");
      out.write("    but let's scoot in the header's buttons\r\n");
      out.write("    */\r\n");
      out.write("    padding-top: 1em;\r\n");
      out.write("    padding-left: 1em;\r\n");
      out.write("    padding-right: 1em;\r\n");
      out.write("  }\r\n");
      out.write("  .resv-content{\r\n");
      out.write("  \tfloat:left;\r\n");
      out.write("  \tposition:relative;\r\n");
      out.write("  }\r\n");
      out.write("\t#calendar-container{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("}\r\n");
      out.write(".resv-submit-div-go button{\r\n");
      out.write("  background:#f8f9fa;\r\n");
      out.write("  color:rgb(241, 209, 209);\r\n");
      out.write("  border:1px solid rgb(241, 209, 209);\r\n");
      out.write("\r\n");
      out.write("  position:relative;\r\n");
      out.write("  height:60px;\r\n");
      out.write("  font-size:1.2em;\r\n");
      out.write("  padding:0 2em;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  transition:800ms ease all;\r\n");
      out.write("  outline:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    	Member m = (Member)session.getAttribute("loginMember");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("     <style>\r\n");
      out.write("    \t @font-face {\r\n");
      out.write("            font-family: 'S-CoreDream-4Regular';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-4Regular.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\t\t@font-face {\r\n");
      out.write("\t\t    font-family: 'Cafe24Danjunghae';\r\n");
      out.write("\t\t    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_twelve@1.1/Cafe24Danjunghae.woff') format('woff');\r\n");
      out.write("\t\t    font-weight: normal;\r\n");
      out.write("\t\t    font-style: normal;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t@font-face {\r\n");
      out.write("\t\t    font-family: 'KCC-eunyoung';\r\n");
      out.write("\t\t    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/KCC-eunyoung-Regular.woff') format('woff');\r\n");
      out.write("\t\t    font-weight: normal;\r\n");
      out.write("\t\t    font-style: normal;\r\n");
      out.write("\t\t}\r\n");
      out.write("        header{\r\n");
      out.write("            width: 100vw;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar {\r\n");
      out.write("            display: block;\r\n");
      out.write("            background-color: #faf2f2;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .logo >h2{\r\n");
      out.write("         \tfont-family: 'Cafe24Danjunghae';\r\n");
      out.write("         }\r\n");
      out.write("        \r\n");
      out.write("        .logo>p{\r\n");
      out.write("        \t font-family: 'KCC-eunyoung';\r\n");
      out.write("        \t font-size: 14pt;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi-menu,\r\n");
      out.write("        .navi-menu-top {\r\n");
      out.write("            /* menu ul */\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi-menu-top {\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi-menu {\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            width: 680px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi-menu>li {\r\n");
      out.write("            width: 125px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi-menu li>a {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: #373a40;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi-menu-top {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-top {\r\n");
      out.write("     \t   \tfont-family: 'S-CoreDream-4Regular';\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            float: right;\r\n");
      out.write("            padding-right: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi-menu-top li {\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi-menu-top li>a {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 9pt;\r\n");
      out.write("            line-height: 30px;\r\n");
      out.write("            color: #373a40;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .subMenu{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            transition-duration: 2s;\r\n");
      out.write("        }\r\n");
      out.write("        .subMenu li>a{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 125px;\r\n");
      out.write("            float: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("        <script>\r\n");
      out.write("        $(function(){\r\n");
      out.write("            var subMenu = $(\".subMenu\");\r\n");
      out.write("            subMenu.hide();\r\n");
      out.write("            \r\n");
      out.write("            $(\".navi-menu>li>a\").hover(function(){\r\n");
      out.write("               $(this).css('color','gray');\r\n");
      out.write("            },function(){\r\n");
      out.write("                $(this).css('color','#373a40');\r\n");
      out.write("           });\r\n");
      out.write("            \r\n");
      out.write("            $(\".navi-menu>li>a\").click(function(){                \r\n");
      out.write("                subMenu.each(function(idx,item){\r\n");
      out.write("                    $(this).hide();\r\n");
      out.write("                })\r\n");
      out.write("                $(this).next().slideToggle();\r\n");
      out.write("             });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("     <div class=\"nav-top\">\r\n");
      out.write("     ");
if(m != null) { //로그인 된 상태
      out.write(" \r\n");
      out.write("     \t<ul class=\"navbar-nav navi-menu-top\" id=\"login-nav\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"nav-top-link\" href=\"/logout\">로그아웃</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            ");
if(m.getMemberLevel() == 0) {
      out.write("\r\n");
      out.write("                <a class=\"nav-top-link\" href=\"/adminPage\">관리자페이지</a>\r\n");
      out.write("            ");
}else{ 
      out.write("\r\n");
      out.write("                <a class=\"nav-top-link\" href=\"/myPage?memberId=");
      out.print(m.getMemberId());
      out.write("\">마이페이지</a>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("     ");
}else { 
      out.write("\r\n");
      out.write("     \t<ul class=\"navbar-nav navi-menu-top\" id=\"logout-nav\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"nav-top-link\" href=\"/views/member/login.jsp\">로그인</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"nav-top-link\" href=\"/views/member/join.jsp\">회원가입</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("     ");
} 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <img src=\"/img/logo.png\" width=\"100px;\" onclick=\"location.href = '/'\">\r\n");
      out.write("            <h2>STUDIO Mood:</h2>\r\n");
      out.write("            <p>감성을 담는 사진관 </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   <nav class=\"navbar navbar-expand-sm sticky-top\">\r\n");
      out.write("        <ul class=\"navbar-nav navi-menu\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\">about</a>\r\n");
      out.write("                <ul class=\"subMenu\">\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"#\">studio 'mood'</a></li>\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"#\">오시는 길</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\">product</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\">gallery</a>\r\n");
      out.write("                <ul class=\"subMenu\">\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"#\">개인프로필</a></li>\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"#\">바디프로필</a></li>\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"#\">단체프로필</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\">reservation</a>\r\n");
      out.write("                <ul class=\"subMenu\">\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"/test\">예약</a></li>\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"/searchReserve\">예약확인</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\">board</a>\r\n");
      out.write("                <ul class=\"subMenu\">\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"/noticeList?reqPage=1\">공지사항</a></li>\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"#\">QnA</a></li>\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"#\">review</a></li>\r\n");
      out.write("                    <li><a class=\"nav-link sub-nav-item\" href=\"#\">FAQ</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"resv-main-frame\">\r\n");
      out.write("    <div class=\"resv-chk\">\r\n");
      out.write("        <a href=\"/test\" class=\"resv-chk-do\">예약하기</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"resv-chk\">\r\n");
      out.write("        <a href=\"/searchReserve\" class=\"resv-chk-do\">예약확인</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"resv-content\">\r\n");
      out.write("  <div id='calendar-container'>\r\n");
      out.write("    <div id='calendar'></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <form name=\"f\" action=\"/reservationLoginChk\">\r\n");
      out.write(" \r\n");
      out.write("<div class=\"resv-select\">\r\n");
      out.write("        <div class=\"resv-chkbox\">\r\n");
      out.write("           <div class=\"resv-selectbox\">\r\n");
      out.write("                <label for=\"resv-concept-select\" id=\"cut-label\">컨셉</label>\r\n");
      out.write("\r\n");
      out.write("                <select name=\"concept\" id=\"resv-concept-select\">\r\n");
      out.write("                    <option selected>원하는 컨셉을 선택하세요</option>\r\n");
      out.write("                    <option value=\"바디프로필\" id=\"body\">바디프로필</option>\r\n");
      out.write("                    <option value=\"개인프로필\" id=\"indiv\">개인프로필</option>\r\n");
      out.write("                    <option value=\"단체사진\" id=\"group\">단체사진</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div> \r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("        <div class=\"resv-cut-option\">\r\n");
      out.write("            <div class=\"resv-selectbox\">\r\n");
      out.write("                <label for=\"resv-select\" id=\"cut-label\">컷수</label>\r\n");
      out.write("\r\n");
      out.write("                <select name=\"cut\" id=\"resv-select\">\r\n");
      out.write("                    <option selected>원하는 컷수를 선택하세요</option>\r\n");
      out.write("                    <option value=\"1\">1</option>\r\n");
      out.write("                    <option value=\"2\">2</option>\r\n");
      out.write("                    <option value=\"3\">3</option>\r\n");
      out.write("                    <option value=\"4\">4</option>\r\n");
      out.write("                    <option value=\"5\">5</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("         <div class=\"resv-time-chk\">\r\n");
      out.write("          <div class=\"resv-day-screen\" value=\"\" name=\"r_date\">\r\n");
      out.write("          \t\r\n");
      out.write("          </div>\r\n");
      out.write("          <input type=\"hidden\" name=\"r_date\" value=\"\">\r\n");
      out.write("          \r\n");
      out.write("                <div class=\"resv-time-list\">\r\n");
      out.write("                   \r\n");
      out.write("                   <label for=\"11\" class=\"labelchk\" value=\"11\">11시\r\n");
      out.write("                        <input type=\"checkbox\" class=\"resv-time-chkbox\" value=11 id=\"11\" style=\"display: none\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"12\" class=\"labelchk\" value=\"12\">12시\r\n");
      out.write("                        <input type=\"checkbox\" class=\"resv-time-chkbox\" value=12 id=\"12\" style=\"display: none\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"1\" class=\"labelchk\" value=\"13\">1시\r\n");
      out.write("                        <input type=\"checkbox\" class=\"resv-time-chkbox\" value=13 id=\"1\" style=\"display: none\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"2\" class=\"labelchk\" value=\"14\">2시\r\n");
      out.write("                        <input type=\"checkbox\" class=\"resv-time-chkbox\" value=14 id=\"2\" style=\"display: none\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"3\" class=\"labelchk\" value=\"15\">3시\r\n");
      out.write("                        <input type=\"checkbox\" class=\"resv-time-chkbox\" value=15 id=\"3\" style=\"display: none\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"resv-time-list\" >\r\n");
      out.write("                  \r\n");
      out.write("                   <label for=\"4\" class=\"labelchk\" value=\"16\">4시\r\n");
      out.write("                        <input type=\"checkbox\" class=\"resv-time-chkbox\" value=16 id=\"4\" style=\"display: none\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"5\" class=\"labelchk\" value=\"17\">5시\r\n");
      out.write("                        <input type=\"checkbox\" class=\"resv-time-chkbox\" value=17 id=\"5\" style=\"display: none\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"6\" class=\"labelchk\" value=\"18\">6시\r\n");
      out.write("                        <input type=\"checkbox\" class=\"resv-time-chkbox\" value=18 id=\"6\" style=\"display: none\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"7\" class=\"labelchk\" value=\"19\">7시\r\n");
      out.write("                        <input type=\"checkbox\" class=\"resv-time-chkbox\" value=19 id=\"7\" style=\"display: none\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"8\" class=\"labelchk\" value=\"20\">8시\r\n");
      out.write("                        <input type=\"checkbox\" class=\"resv-time-chkbox\" value=20 id=\"8\" style=\"display: none\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        <div class=\"resv-submit\">\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"resv-submit-div-price\">\r\n");
      out.write("                        <input type=\"text\" class=\"resv-submit-input\" id=\"resv-submit-input-text\" readonly>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"resv-submit-div-pw\">\r\n");
      out.write("                        <input type=\"password\" id=\"resv-submit-input-pass\" class=\"resv-submit-input\" name=\"r_pass\" required placeholder=\"4자리 비밀번호\" minlength=\"4\" maxlength=\"4\" pattern=\"[0-9]+\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"resv-submit-div-go\">\r\n");
      out.write("                        <button type=\"submit\" class=\"resv-submit-input\">예약하기</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("            <input type=\"hidden\" id=\"sendstartday\" name=\"s_time\" value=\"\">\r\n");
      out.write("            <input type=\"hidden\" id=\"sendendday\" name=\"e_time\" value=\"\">\r\n");
      out.write("            ");
if(r!=null){
      out.write("\r\n");
      out.write("            <input type=\"hidden\" id=\"sendrCheck\" name=\"rCheck\" value=\"");
      out.print(r.getrCheck());
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" id=\"sendrNum\" name=\"rNum\" value=\"");
      out.print(r.getrNum());
      out.write("\">\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t\t @font-face {\r\n");
      out.write("            font-family: 'S-CoreDream-4Regular';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-4Regular.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: 'S-CoreDream-5Medium';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-5Medium.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("        .footer{\r\n");
      out.write("            background-color: rgb(124, 117, 117);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 100vw;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .footerBox{\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            display: inline-block\r\n");
      out.write("        }\r\n");
      out.write("        .footerBox >h2{\r\n");
      out.write("       \t\tfont-family: 'S-CoreDream-5Medium';\r\n");
      out.write("            color: rgb(241, 209, 209);\r\n");
      out.write("            font-size: 18pt;\r\n");
      out.write("        }\r\n");
      out.write("        .footerBox>p{\r\n");
      out.write("        \tfont-family: 'S-CoreDream-4Regular';\r\n");
      out.write("        \tfont-size: 9pt;\r\n");
      out.write("            color: rgb(241, 238, 238);\r\n");
      out.write("        }\r\n");
      out.write("        .footer-top,\r\n");
      out.write("        .footer-bottom{\r\n");
      out.write("        \tmargin : 0 auto;\r\n");
      out.write("            width: 1198px;\r\n");
      out.write("        }\r\n");
      out.write("        .footer-bottom{\r\n");
      out.write("          color: rgba(241, 238, 238, 0.8);\r\n");
      out.write("          font-size: 10pt;\r\n");
      out.write("        }\r\n");
      out.write("        .icon{\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .icon>img{\r\n");
      out.write("            \r\n");
      out.write("            width: 50px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <footer>\r\n");
      out.write("       <div class=\"footer\">\r\n");
      out.write("           <div class=\"footer-top\">\r\n");
      out.write("                <div class=\"footerBox company-info\" width:310px;>\r\n");
      out.write("                <h2>COMPANY INFO</h2>\r\n");
      out.write("                <p>\r\n");
      out.write("                    Company : 스튜디오무드 <br>\r\n");
      out.write("                    Business-License : 888-999-33333<br>\r\n");
      out.write("                    Tel: 02-3333-5555<br>\r\n");
      out.write("                    Email : mood_studio@gmail.com<br>\r\n");
      out.write("                    Addr : 서울특별시 강남구 사진관로 34번길<br>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footerBox bank-info\" width:180px;>\r\n");
      out.write("                <h2>BANK INFO</h2>\r\n");
      out.write("                <p>\r\n");
      out.write("                    농협 : 333-8888-5555-44 <br>\r\n");
      out.write("                    국민 : 888999-01-33333<br><br>\r\n");
      out.write("                    예금주: 스튜디오 분위기<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footerBox cs\" width:230px;>\r\n");
      out.write("                <h2>CS CENTER</h2>\r\n");
      out.write("                <p>\r\n");
      out.write("                    tel : 010-2222-5555 <br>\r\n");
      out.write("                    mail : mood_studio@gmail.com<br><br><br><br>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("           <div class=\"footerBox icon\" width:130px;>    \r\n");
      out.write("               <img src=\"/img/Facebook_1.png\">\r\n");
      out.write("               <img src=\"/img/Twitter_1.png\">\r\n");
      out.write("               <img src=\"/img/Instagram_1.png\">\r\n");
      out.write("               <p><br><br><br><br></p>\r\n");
      out.write("           </div>\r\n");
      out.write("           </div>\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"footer-bottom\">\r\n");
      out.write("                <p>Copyright &copy; 2020 by Studiomood All Right Reserved</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("   </footer>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var option;\r\n");
      out.write("var startDay = $(\"#sendstartday\").attr(\"value\");\r\n");
      out.write("var endDay = $(\"#sendendday\").attr(\"value\");\r\n");
      out.write("var picPrice = 0;\r\n");
      out.write("var cutPrice = 0;\r\n");
      out.write("var timePrice = 0;\r\n");
      out.write("\r\n");
      out.write("window.onload = function() {\r\n");
      out.write("    $(\"#resv-submit-input-text\").attr(\"value\", \"가격: \"+(picPrice + cutPrice + timePrice) + \"원\");\r\n");
      out.write("};\r\n");
      out.write("//컨셉의 가격표\r\n");
      out.write("\r\n");
      out.write("//컷수당의 가격수\r\n");
      out.write("$('select[name=\"cut\"]').change(function() {\r\n");
      out.write("    cutPrice = $(this).val() * 1000;\r\n");
      out.write("    $(\"#resv-submit-input-text\").attr(\"value\", \"가격: \"+(picPrice + cutPrice + timePrice) + \"원\");\r\n");
      out.write("});\r\n");
      out.write("//시작과 끝시간\r\n");
      out.write("$(\".labelchk\").click(function() {\r\n");
      out.write("    if (endDay > 0 && startDay > 0) {\r\n");
      out.write("        timePrice = (endDay - startDay) * 100000;\r\n");
      out.write("        $(\"#resv-submit-input-text\").attr(\"value\", \"가격: \"+(picPrice + cutPrice + timePrice) + \"원\");\r\n");
      out.write("    } else {\r\n");
      out.write("        timePrice = 0;\r\n");
      out.write("        $(\"#resv-submit-input-text\").attr(\"value\", \"가격: \"+(picPrice + cutPrice + timePrice) + \"원\");\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("    \r\n");
      out.write("    $('button[type=\"submit\"]').click(function(){\r\n");
      out.write("        console.log($(\"#sendstartday\").val());\r\n");
      out.write("        console.log(endDay);\r\n");
      out.write("        if(document.f.cut.value==\"\"||$(\"#sendstartday\").val()==null||$(\"#sendstartday\").val()==0||$(\"#sendendday\").val()==null||$(\"#sendendday\").val()==0||document.f.concept.value==\"\"){\r\n");
      out.write("            alert(\"다시\");\r\n");
      out.write("           return false;\r\n");
      out.write("        }\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
