/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-12-02 05:16:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>[STUDIO Mood:]admin_</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Black+Han+Sans&display=swap&subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: 'Wemakeprice-Bold';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10-21@1.0/Wemakeprice-Bold.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: 'GmarketSansMedium';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/GmarketSansMedium.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .admin-menu {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            height: 100vw;\r\n");
      out.write("            background-color: #9f807d;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .div1 {\r\n");
      out.write("            height: 20%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .menuBox {\r\n");
      out.write("            height: 600px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .menu {\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-title {\r\n");
      out.write("            font-family: 'Wemakeprice-Bold';\r\n");
      out.write("            font-size: 20pt;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #56373c;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .icon {\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .menu li>a {\r\n");
      out.write("            font-family: 'GmarketSansMedium';\r\n");
      out.write("            display: block;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            line-height: 45px;\r\n");
      out.write("            font-size: 10pt;\r\n");
      out.write("            color: #391e22;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .menu>li {\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            text-indent: 10px;\r\n");
      out.write("            padding-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .div2 {\r\n");
      out.write("            height: 28%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .admin-content {\r\n");
      out.write("            text-indent: 20px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            height: 100vw;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .real-content>p {\r\n");
      out.write("            font-family: 'Black Han Sans';\r\n");
      out.write("            font-size: 50pt;\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .real-content>p>span {\r\n");
      out.write("            font-family: 'Black Han Sans';\r\n");
      out.write("            font-size: 45pt;\r\n");
      out.write("            margin-top: 100px;\r\n");
      out.write("            color: #56373c;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .real-content>span {\r\n");
      out.write("            font-family: 'GmarketSansMedium';\r\n");
      out.write("            margin: 30px;\r\n");
      out.write("            font-size: 20pt;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function() {\r\n");
      out.write("            $(\".menu li>a\").hover(function() {\r\n");
      out.write("                $(this).parent().css('background-color', '#d0b0b1');\r\n");
      out.write("            }, function() {\r\n");
      out.write("                $(this).parent().css('background-color', '#9f807d');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"admin-wrap\">\r\n");
      out.write("        <!--화면 좌측-->\r\n");
      out.write("        <div class=\"admin-menu\">\r\n");
      out.write("            <div class=\"div1\"></div>\r\n");
      out.write("            <div class=\"menuBox\">\r\n");
      out.write("                <img class=\"circle profile\" src=\"img/admin.svg\" width=\"100px;\">\r\n");
      out.write("                <div class=\"profile-title\">\r\n");
      out.write("                    admin\r\n");
      out.write("                </div><br><br>\r\n");
      out.write("                <ul class=\"menu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/\">\r\n");
      out.write("                            <img src=\"img/icon_Home.svg\" class=\"icon\">\r\n");
      out.write("                            <span>STUDIO Mood:</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/adminMembers?reqPage=1\">\r\n");
      out.write("                            <img src=\"img/icon_members.svg\" class=\"icon\">\r\n");
      out.write("                            MEMBERS\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <img src=\"img/icon_reservation.svg\" class=\"icon\">\r\n");
      out.write("                            RESERVATION\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <img src=\"img/icon_Notice.svg\" class=\"icon\">\r\n");
      out.write("                            NOTICE\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"div1\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--화면 우측-->\r\n");
      out.write("        <div class=\"admin-content\">\r\n");
      out.write("            <div class=\"div2\"></div>\r\n");
      out.write("            <div class=\"real-content\">\r\n");
      out.write("                <p>STUDIO <span>Mood:</span></p><br>\r\n");
      out.write("                <span>admin page</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"div2\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
